development:
  adapter: postgresql
  database: linku_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: linku_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: linku_production
  pool: 5
  timeout: 5000

