default: &default
  pool: 5
  timeout: 5000
  username: uninortehorarios
  adapter: sqlite3
development:
  <<: *default
  database: linku_development
test:
  <<: *default
  database: linku_test
production:
  pool: 50
  timeout: 5000
  username: postgres
  adapter: postgresql
  database: linku_production
