default: &default
  pool: 5
  timeout: 5000
  username: postgres
  adapter: postgresql
development:
  <<: *default
  database: linku_development
test:
  <<: *default
  database: linku_test
production:
  <<: *default
  pool: 50
  database: linku_production

